### ISSUE TITLE
v1.2.4 production ready

### ISSUE THREAD

**Issue by mkevenaar** [zbx-sadman/WSFC#2]
Hi,

Would you be able to provide an estimate when the v1.2.4 would be production ready?

Thanks,

Maurice

**Comment by zbx-sadman** [comment]
Hello

Generally - v1.2.4 (script & template) is works on my Win2008R2 cluster for some weeks. However, i have no access to other cluster's or user reports and can't guarantee script properly works on other Windows releases. 

Script still placed in /dev because i have a pair of ideas, but i haven't time to implementaton.

**Comment by mkevenaar** [comment]
I can confirm that v1.2.4 works on our clusters. We are running WS16.
